### ISSUE TITLE
Can't build/serve on Windows 10, spawn bundle ENOENT error

### ISSUE THREAD

**Issue by adrivn** [taylorbryant/jekyll-starter-tailwind#64]
Hi Taylor
First of all thanks for your work in putting together this bundle. I seldom open issues in Github, but I'm trying to start a project of my own and your solution seems almost tailor-made for my purposes. Sadly I use Windows 10, so when I run **npm run start** I get this:

`λ npm run start
> jekyll-starter-tailwind@5.0.12 start c:\Playground\StaticSites\tw
> gulp serve
[18:39:11] Requiring external module babel-register
[18:39:12] Using gulpfile c:\Playground\StaticSites\tw\gulpfile.babel.js
[18:39:12] Starting 'serve'...
[18:39:12] Starting 'buildJekyll'...
[18:39:12] 'buildJekyll' errored after 13 ms
[18:39:12] Error: spawn bundle ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[18:39:12] 'serve' errored after 23 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jekyll-starter-tailwind@5.0.12 start: `gulp serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jekyll-starter-tailwind@5.0.12 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

What do you think might be causing this?

**Comment by taylorbryant** [comment]
This should be fixed now: https://github.com/taylorbryant/jekyll-starter-tailwind/blob/master/gulpfile.babel.js#L22

**Comment by jacquescorbytuech** [comment]
Hi taylor, 

Thanks for creating this starter theme, it's been hugely helpful!

I still get the same error as adrivn with the new script, I was able to partially make this work after adding the following packages from npm:

win-node-env
win-spawn

Unfortunately I still get an error when trying to run "npm run build" locally on my machine or on Netlify, this is what Netlify returns when trying to deploy:

> 9:54:46 PM: Verify run directory
> 9:54:46 PM: Executing user command: npm run build
> 9:54:46 PM: npm
> 9:54:46 PM: ERR!
> 9:54:46 PM:  missing script: build

I can confirm the script is running against the correct directory.
